### ISSUE TITLE
Allow "Sequential Proxy" feature to work with POST, PUT and DELETE methods.

### ISSUE THREAD

**Issue by antonincms** [luraproject/lura#359]
Hello,

**Is your feature request related to a problem? Please describe.**
I am working on a proof of concept for my company (as an intern), and one interesting feature for me in krakend was the sequential proxy feature, because I hoped it allows us to submit a POST to a microservice of my stack (in order to verify it) before transmitting to the final microservice (the one that should handle the POST).

For the record, here is an example of my configuration : 
```yaml
"version": 2
"port": 80
"extra_config":
  "github_com/devopsfaith/krakend-gologging":
    "level": "INFO"
    "prefix": "[MY-PROXY]"
    "stdout": true
"endpoints":
  - "endpoint": "/myservice/v1/myobject"
    "extra_config":
      "github.com/devopsfaith/krakend/proxy":
        "sequential": true
    "method": "POST"
    "output_encoding": "json"
    "backend":
      - "url_pattern": "/v1/check/myservice/v1/myobject"
        "encoding": "json"
        "method": "POST"
        "host": [ "http://checker:80" ]
      - "url_pattern": "/v1/my_object_to_post"
        "encoding": "json"
        "method": "POST"
        "host": [ "http://myservice:90" ]
```

But Krakend or the Proxy plugin has the behavior to refuse that : 
```
[MYPROXY] 2020/04/29 - 14:42:43.871 ▶ ERROR POST endpoints must have a single backend! Ignoring /myservice/v1/myobject
```

**Describe the solution you'd like**
The error I get is logical for a concurrent request to several backend, but in the other hand, my use case doesn't seem that far from the base usage of the sequential proxy (which is to query a variable from a first backend in order to query a second one). 

The error seems to be sent from [here](https://github.com/devopsfaith/krakend/blob/master/router/chi/router.go) line 126, so in the core. I'd like to have the option say explicitely that I wan't that kind of behavior (as with a `"allow_multiple_backends" : true`), or I'd like the plugin to be able to ask such behavior.

I must say that I know too little about the code of krakend atm for having a precise idea of what would be possible.

**Describe alternatives you've considered**
The other possibility is probably to develop our own plugin for it, but as the use case seems not that far from the [documented one](https://www.krakend.io/docs/endpoints/sequential-proxy/), it would be maybe preferable to make this usecase possible with the current toolset.

Thank you for reading
-- Antonin
